apiVersion: apps/v1
kind: Deployment
metadata:
  name: slider-deployment
  namespace: slider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slider
  template:
    metadata:
      labels:
        app: slider
    spec:
      containers:
      - name: slider
        image: cs125/slider:2019.12.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: TZ
          value: "America/Chicago"
        - name: ENVIRONMENT
          value: "production"
        - name: MONGODB
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: MONGODB
        - name: GOOGLE
          value: 948918026196-p399ooibc7pr0ci7ida63jb5a6n4vsik.apps.googleusercontent.com
---
apiVersion: v1
kind: Service
metadata:
  name: slider-service
  namespace: slider
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: slider
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: slider
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-redirect-from: /
    nginx.ingress.kubernetes.io/proxy-redirect-to: /slider/
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: slider-ingress
spec:
  rules:
  - http:
      paths:
      - path: /slider(/|$)(.*)
        backend:
          serviceName: slider-service
          servicePort: 80
